// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package starland_points_v1

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ClaimPoints is the `claimPoints` instruction.
type ClaimPoints struct {
	Amount    *uint64
	Signature *[96]uint8

	// [0] = [WRITE] userPoints
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewClaimPointsInstructionBuilder creates a new `ClaimPoints` instruction builder.
func NewClaimPointsInstructionBuilder() *ClaimPoints {
	nd := &ClaimPoints{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *ClaimPoints) SetAmount(amount uint64) *ClaimPoints {
	inst.Amount = &amount
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *ClaimPoints) SetSignature(signature [96]uint8) *ClaimPoints {
	inst.Signature = &signature
	return inst
}

// SetUserPointsAccount sets the "userPoints" account.
func (inst *ClaimPoints) SetUserPointsAccount(userPoints ag_solanago.PublicKey) *ClaimPoints {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(userPoints).WRITE()
	return inst
}

// GetUserPointsAccount gets the "userPoints" account.
func (inst *ClaimPoints) GetUserPointsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *ClaimPoints) SetAuthorityAccount(authority ag_solanago.PublicKey) *ClaimPoints {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *ClaimPoints) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst ClaimPoints) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ClaimPoints,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ClaimPoints) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ClaimPoints) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.UserPoints is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *ClaimPoints) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ClaimPoints")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("Signature", *inst.Signature))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("userPoints", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj ClaimPoints) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ClaimPoints) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	return nil
}

// NewClaimPointsInstruction declares a new ClaimPoints instruction with the provided parameters and accounts.
func NewClaimPointsInstruction(
	// Parameters:
	amount uint64,
	signature [96]uint8,
	// Accounts:
	userPoints ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *ClaimPoints {
	return NewClaimPointsInstructionBuilder().
		SetAmount(amount).
		SetSignature(signature).
		SetUserPointsAccount(userPoints).
		SetAuthorityAccount(authority)
}
